[Tools 2088] backup/restore Sindex with ctx
aerospike/aerospike-tools-backup pull request #32
Opened 2022-09-08 17:54 UTC by atefehmohseni

2022-09-08 18:07 UTC, atefehmohseni commented
Comments on the same PR:

https://github.com/aerospike/aerospike-tools-backup/pull/28#issuecomment-1240017329

https://github.com/aerospike/aerospike-tools-backup/pull/28#issuecomment-1241053849

2022-09-08 22:30 UTC, atefehmohseni reviewed
review comments from the review session with Jesse and Dylan

2022-09-08 22:30 UTC, atefehmohseni commented on src/dec_text.c
> +	if (!text_nul_read_token(fd, false, line_no, col_no, ctx, sizeof ctx, "\n")) {
add tests to call old backup files (that dont have ctx at the end of sindex records)

2022-09-08 22:30 UTC, atefehmohseni commented on src/enc_text.c
> +	if (io_proxy_printf(fd, " %s\n", index->ctx != NULL ? escape(index->ctx) : "") < 0) {
separate the "\n" write to be explicit

2022-09-08 22:30 UTC, atefehmohseni commented on src/backup.c
> +	char* b64_enable = ";b64=true";
test if older server versions would take "b64=true"

2022-09-08 22:30 UTC, atefehmohseni commented on src/utils.c
> -		} else if (strcmp(para, "bin") == 0) {
consider "path" apart from "bin" from sindex-list server response.

2022-09-08 22:30 UTC, atefehmohseni commented on src/restore.c
> -	size_t value_size = sizeof "sindex-list:ns=" - 1 + strlen(index->ns) + 1;
"b64=true" with older server test -> asrestore behavior?

2022-09-08 22:30 UTC, atefehmohseni commented on src/restore.c
> +	if (!index->ctx && index->ctx != index2.ctx) {
condition "!index->ctx" needed to be refined. 
get rid of the first check
check str<>str not pointer to pointer

2022-09-08 22:30 UTC, atefehmohseni commented on src/restore.c
> -
destroy cdt_ctx if no error occurs too

2022-09-08 22:30 UTC, atefehmohseni commented on test/unit/test_utils.c
> +START_TEST(test_secondary_index_param_with_ctx)
add a unit test to sindex record without "context" in server response (index->ctx be null)

2022-09-14 22:25 UTC, dwelch-spike requested changes
A few comments/questions. Looks good otherwise.

2022-09-14 22:25 UTC, dwelch-spike commented on src/restore.c
> +static bool compare_strs(const char *set1, const char *set2);
the parameters are still names `set` and `set2` despite being changed in the definition.

2022-09-14 22:25 UTC, dwelch-spike commented on src/restore.c
> +static bool compare_strs(const char *set1, const char *set2);
Params still called `set1` and `set2`

2022-09-14 22:25 UTC, dwelch-spike commented on src/restore.c
> +	if (!compare_strs(index->ctx, index2.ctx)) {
With the new check, won't this enter the body of the if statement if both `index->ctx` and `index2.ctx` are NULL (null pointers)? Is that expected?

2022-09-14 22:25 UTC, dwelch-spike commented on src/utils.c
> +		//inf("Couldn't move record key values (reference count > 1).");
Should this be commented?

2022-09-14 22:26 UTC, dwelch-spike commented on src/restore.c
> +static bool compare_strs(const char *set1, const char *set2);
duplicate

2022-09-15 15:58 UTC, merged